### ISSUE TITLE
`undefined is not iterable...` on text hover

### ISSUE THREAD

**Issue by davorpa** [lostintangent/gistpad#262]
Hi

Thanks for this great extension!

I don't know if this happens to anybody more but I have the IDE's log console plenty of the stacktrace seen below.

Extension is capable of fetch my gitsts and edit it.

**To Reproduce**
1. Open any text file. I'd checked it with a `.md` (markdown)
2. Wait for the Intellisense suggestions
3. Check errors on `Output` panel > `Log (Window)` / `Log (Extension Hosts)`

**Expected behavior**
No console errors or more context about it to know about solve it

**Screenshots**

**Desktop (please complete the following information):**
 - VS Code: 
    Version: `1.62.3 (system setup)`
    Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
    Date: 2021-11-17T08:11:14.551Z
    Electron: 13.5.2
    Chrome: 91.0.4472.164
    Node.js: 14.16.0
    V8: 9.1.269.39-electron.0
    OS: Windows
 - GistPad Version: `v0.3.0`

**Additional context**

```logs
[2021-11-27 16:11:38.475] [exthost] [error] [vsls-contrib.gistfs] provider FAILED
[2021-11-27 16:11:38.476] [exthost] [error] undefined is not iterable (cannot read property Symbol(Symbol.iterator)): TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at o.provideHover (\user\.vscode\extensions\vsls-contrib.gistfs-0.3.0\dist\extension.js:51:186784)
    at d.provideHover (\vscode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:170537)
    at \vscode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:194656
    at $e._withAdapter (\vscode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:191442)
    at $e.$provideHover (\vscode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:194634)
    at n._doInvokeHandler (\vscode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:98:13802)
   ...
```

**Comment by lostintangent** [comment]
I'm not able to repro this issue, so I'm going to close it for now. Please re-open it if you're still experiencing an issue, and could share any further repro steps. Thanks!
